### ISSUE TITLE
Suggestion: Add "Why" section to README

### ISSUE THREAD

**Issue by iansinnott** [taion/rrtr#5]
I read your [blog post](https://medium.com/@taion/react-router-is-dead-long-live-rrtr-d229ca30e318#.8byxvbzo6). That definitely provides some insight into why you created this lib, but considering many people coming here are likely existing users of React Router it might be nice to include a section in the README dedicated to giving some background on why this project exists and the pain points you are trying to solve. My guess is it would preempt a lot of questions people will be having.

I realize this is brand new. Just a thought.

**Comment by taion** [comment]
What do you think of #6? It's the note I've added to all of my other libs.

**Comment by iansinnott** [comment]
The link should definitely help answer peoples questions. 👍
